### ISSUE TITLE
Inline variable is not formated correctly

### ISSUE THREAD

**Issue by lorentsi** [dmar1n/lazy-log#1]
When applying the formatter to log that looks like 

`logger.info(f"My example string {example_string=}")`

it is formatted as 

`logger.info("My example string %s", example_string=)` which cause an error due to = sign.

Expected output:

`logger.info("My example string %s", example_string)` or `logger.info("My example string example_string=%s", example_string)`

**Comment by dmar1n** [comment]
Thanks for reporting, @lorentsi! Fixed in 0.4.3
